version: "3.6"

services: # docker-compose up web database redis sidekiq
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' -p 3000"
    restart: always
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    links:
      - "database"
      - "redis"
    env_file:
      - ".env"
  database:
    image: postgres:latest
    restart: always
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432"
    env_file:
      - ".env"
  redis:
    image: redis:latest
    restart: always
    volumes:
      - "redis:/data"
    ports:
      - "6379"

volumes:
  redis:
  postgres:
